// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as ExpoStatusBar from "expo-status-bar";

function App$app(Props) {
  return React.createElement(ReactNative.View, {
              style: {
                backgroundColor: "#fff",
                alignItems: "center",
                flex: 1,
                justifyContent: "center"
              },
              children: null
            }, React.createElement(ReactNative.Text, {
                  children: "Open up src/app.res to start working on your app!"
                }), React.createElement(ExpoStatusBar.StatusBar, {
                  style: "auto"
                }));
}

var app = App$app;

export {
  app ,
  
}
/* react Not a pure module */
